# Generated by Django 3.1.1 on 2021-06-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bharti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=True, max_length=50)),
                ('lname', models.TextField(default=True, max_length=100)),
            ],
        ),
    ]
