# Generated by Django 3.1.1 on 2021-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formunderstand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bharti',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
